var wedding = [
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/_MG_1620.jpg','captions':'Couple''s Secret Talk'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/Im1%20(16).jpg','captions':'Impana - Vivek'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/chethan(19).jpg','captions':'Chethan - Andria'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/prachi001(18).jpg','captions':'Prachi - Abhay'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/r1%20(1).jpg','captions':'Rajeshwari - Praveen'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/sanjal(3).jpg','captions':'Sanjal - Vikas'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/za.jpg','captions':'Prasad - Mamatha'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/0005.jpg','captions':'Madhu -Vinaya'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/_MG_2419.jpg','captions':'Brides like baby'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/002.jpg','captions':'Akshate in wedding'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/IMG_2805.jpg','captions':'Dharshana - Pavan'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/031.jpg','captions':'Megha - Kunal'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/1.jpg','captions':'Namratha - Navin'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/img_4772.jpg','captions':'Akash - Deepika(Belgaum)'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/JE0A9170.jpg','captions':'Ashwini - Santhosh'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/10.jpg','captions':'Athul - Smitha'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/MCKL2389.jpg','captions':'Divya - Harsha'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/IMG_2387.jpg','captions':'Jagan - Abhinaya'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/001.jpg','captions':'Santhu - Deepa'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/07.jpg','captions':'Manoj - Rajeshwari'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/JE0A1128.jpg','captions':'Jahnavi'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/02.jpg','captions':'Jyothi - Rudresh'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/IMG_2933 copy.jpg','captions':'Kavya - Sharath'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/104.jpg','captions':'Kausalya'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/06.jpg','captions':'Dharshana - Siddharth'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/403.jpg','captions':'Neha - Navneeth (Hubballi)'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/11.jpg','captions':'Rakesh'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/IMG_9805.jpg','captions':'Rashmi - Santhosh'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/IMG_5707 copy.jpg','captions':'Vidya - Pramod'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/VSL_8923.jpg','captions':'Uday Mantur'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/JE0A1112.jpg','captions':'Swathi wedding'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/JE0A7219.jpg','captions':'Sahana Vijaykumar'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/JE0A3484.jpg','captions':'Shilpa Santhosh'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/59.jpg','captions':'Dr.Raj Hemanth - Dr.Savitha'},
//  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':''},
 // {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':''},
 // {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':''},

];

var banner =[
  'http://shivuweddingphotography.com/mobile/gallery/001.jpg',
  'http://shivuweddingphotography.com/mobile/gallery/002.jpg',
  "http://shivuweddingphotography.com/mobile/gallery/003.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/004.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/005.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/006.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/007.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/008.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/009.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/010.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/011.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/012.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/013.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/014.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/015.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/016.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/017.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/018.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/019.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/020.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/021.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/022.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/023.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/024.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/025.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/026.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/027.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/028.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/029.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/030.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/031.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/032.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/033.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/034.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/035.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/036.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/037.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/038.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/039.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/040.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/041.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/042.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/043.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/044.jpg"];

var photodetails=[
{"couples":"http://shivuweddingphotography.com/uploads/msmall/big2/019_resize.jpg"},
{"couples": "http://shivuweddingphotography.com/uploads/msmall/big2/030_resize.jpg"},
{"couples": "http://shivuweddingphotography.com/uploads/msmall/big2/040_resize.jpg"},
{"couples": "http://shivuweddingphotography.com/uploads/msmall/big2/IMG_0767.jpg"},
{"couples": "http://shivuweddingphotography.com/uploads/msmall/big2/031_resize.jpg"},
{"couples": "http://shivuweddingphotography.com/uploads/msmall/big2/_MG_1620.jpg"},
{ "couples":"http://shivuweddingphotography.com/uploads/msmall/big2/003.jpg"},
{"couples": "http://shivuweddingphotography.com/uploads/msmall/big2/002.jpg"},
{"couples": "http://shivuweddingphotography.com/uploads/msmall/big2/IMG_1051.jpg"},
{"couples": "http://shivuweddingphotography.com/uploads/msmall/big2/IMG_1388.jpg"},
{"couples": "http://shivuweddingphotography.com/uploads/msmall/big2/IMG_1433.jpg"},
{"couples": "http://shivuweddingphotography.com/uploads/msmall/big2/Wedding_candid_couple%202.jpg"},
{"couples": "http://shivuweddingphotography.com/uploads/msmall/big2/_MG_4239.jpg"},
{"couples":  "http://shivuweddingphotography.com/uploads/msmall/big2/001.jpg"},
{ "couples":"http://shivuweddingphotography.com/uploads/msmall/big2/6x9-pad.jpg"},
{"couples": "http://shivuweddingphotography.com/uploads/msmall/big2/010.jpg"}];