var photos = [
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/_MG_1620.jpg','captions':'Couple''s Secret Talk'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/Im1%20(16).jpg','captions':'Impana - Vivek'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/chethan(19).jpg','captions':'Chethan - Andria'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/prachi001(18).jpg','captions':'Prachi - Abhay'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/r1%20(1).jpg','captions':'Rajeshwari - Praveen'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/sanjal(3).jpg','captions':'Sanjal - Vikas'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/za.jpg','captions':'Prasad - Mamatha'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Madhu -Vinaya'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Brides like baby'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Akshate in wedding'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Dharshana - Pavan'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Megha - Kunal'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Namratha - Navin'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Akash - Deepika(Belgaum)'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Ashwini - Santhosh'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Athul - Smitha'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Divya - Harsha'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Jagan - Abhinaya'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Santhu - Deepa'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Manoj - Rajeshwari'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Jahnavi'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Jyothi - Rudresh'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Kavya - Sharath'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Kausalya'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Dharshana - Siddharth'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Neha - Navneeth (Hubballi)'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Rakesh'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Rashmi - Santhosh'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Vidya - Pramod'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Uday Mantur'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Swathi wedding'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Sahana Vijaykumar'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Shilpa Santhosh'},
  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':'Dr.Raj Hemanth - Dr.Savitha'},
//  {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':''},
 // {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':''},
 // {'photo':'http://www.shivuweddingphotography.com/uploads/albumcover/','captions':''},

];

var banner =[
  'http://shivuweddingphotography.com/mobile/gallery/001.jpg',
  'http://shivuweddingphotography.com/mobile/gallery/002.jpg',
  "http://shivuweddingphotography.com/mobile/gallery/003.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/004.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/005.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/006.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/007.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/008.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/009.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/010.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/011.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/012.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/013.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/014.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/015.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/016.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/017.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/018.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/019.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/020.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/021.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/022.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/023.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/024.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/025.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/026.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/027.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/028.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/029.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/030.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/031.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/032.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/033.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/034.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/035.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/036.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/037.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/038.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/039.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/040.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/041.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/042.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/043.jpg",
  "http://shivuweddingphotography.com/mobile/gallery/044.jpg"];